/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Deposit.java
 *
 * Created on 26 Jul, 2014, 12:01:33 AM
 */
package bankmanagement;
import connection.Connect;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Kashmir Singh
 */
public class Deposit extends javax.swing.JInternalFrame {

    /** Creates new form Deposit */
    public Deposit() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    String date;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        acc_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        tr_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        deposit = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Deposit Money");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(-10197846,true));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel7.setForeground(new java.awt.Color(-1,true));
        jLabel7.setText("Deposit Money");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(-1,true));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true), 3));

        acc_id.setFont(new java.awt.Font("Dialog", 0, 18));
        acc_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_idActionPerformed(evt);
            }
        });
        acc_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                acc_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                acc_idKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel1.setText("Account ID");

        label.setFont(new java.awt.Font("Dialog", 2, 14));
        label.setForeground(new java.awt.Color(-65536,true));

        tr_id.setEditable(false);
        tr_id.setFont(new java.awt.Font("Dialog", 0, 14));
        tr_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tr_idActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel3.setText("Transaction ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tr_id)
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acc_id, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tr_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(acc_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(-1,true));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true), 3));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel2.setText("Customer Name");

        balance.setEditable(false);
        balance.setFont(new java.awt.Font("Dialog", 0, 14));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel4.setText("Balance");

        c_name.setEditable(false);
        c_name.setFont(new java.awt.Font("Dialog", 0, 14));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel6.setText("Deposit Amount");

        deposit.setFont(new java.awt.Font("Dialog", 0, 14));
        deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionPerformed(evt);
            }
        });
        deposit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                depositKeyTyped(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(-10197846,true));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton2.setForeground(new java.awt.Color(-1,true));
        jButton2.setText("DEPOSIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(-10197846,true));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton1.setForeground(new java.awt.Color(-1,true));
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel5.setText("Date");

        dateField.setEditable(false);
        dateField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jButton1)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(c_name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(balance, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deposit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(dateField, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton2)))
                .addGap(191, 191, 191))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(c_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, 0, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_depositActionPerformed

private void acc_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acc_idKeyTyped
// TODO add your handling code here:
     if(!Character.isDigit(evt.getKeyChar()))
    {
        evt.consume();   
    }
}//GEN-LAST:event_acc_idKeyTyped

private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
// TODO add your handling code here:
    tr_id.setEditable(false);
    c_name.setEditable(false);
    balance.setEditable(false);
    dateField.setEditable(false);
    try
    {
        Connect.getConnection();
        String query = "select count(*) from transaction1";
        ResultSet rs = Connect.st.executeQuery(query);
        rs.first();
        int count = rs.getInt(1);
        rs.close();
        if(count==0)
        {
            tr_id.setText(String.valueOf(count+100));
        }
        else
        {
            String query1 = "select * from transaction1";
            rs = Connect.st.executeQuery(query1);
            rs.last();
            tr_id.setText(String.valueOf((Integer.parseInt(rs.getString(1)))+1));
            
        }
       date=DateToday.getDate(); 
       dateField.setText(DateToday.day+"-"+DateToday.monthName+"-"+DateToday.year);
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
}//GEN-LAST:event_formInternalFrameOpened

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
   dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void acc_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acc_idKeyReleased
// TODO add your handling code here:
     if(!acc_id.getText().trim().equals(""))
     {
       try
       {
        
        Connect.getConnection();
        String query = "select name,balance from new_account where account='"+acc_id.getText()+"'";
        ResultSet rs = Connect.st.executeQuery(query);
        if(rs.next())
        {
            label.setText("valid Account ID");
            c_name.setText(rs.getString("name"));
            balance.setText(rs.getString("balance"));
        } 
        else
        {
        label.setText("invalid account ID");    
        c_name.setText("");
        balance.setText("");
        }
    }   
        catch(Exception e)
        {
            System.out.println(e);
        }
     }
    else
    {
       label.setText("Enter account Id");
    }
}//GEN-LAST:event_acc_idKeyReleased

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    
    try
    {
        if(!acc_id.getText().trim().equals(""))
    {
        Connect.getConnection();
        String query = "select name,balance from new_account where account='"+acc_id.getText()+"'";
        ResultSet rs = Connect.st.executeQuery(query);
        if(rs.next())
        {
            c_name.setText(rs.getString("name"));
            balance.setText(rs.getString("balance"));
            rs.close();
            
         }
            else 
            {
            JOptionPane.showMessageDialog(rootPane,"Enter correct Account ID");
            acc_id.setText("");
            return;
            }
    }
       else
        {
            JOptionPane.showMessageDialog(rootPane,"Enter Account Id to be deleted");
            return;
         }
        
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    
    if(deposit.getText().equals(""))
    {
        JOptionPane.showMessageDialog(rootPane,"Enter the amount to be deposited ");
        return;
    }
    else if(deposit.getText().length()<3)
    {
        JOptionPane.showMessageDialog(rootPane,"Minimum limit to deposit money is Rs.100 ");
        deposit.setText("");
        return;
    }
    
    int b = Integer.parseInt(balance.getText());
    int d = Integer.parseInt(deposit.getText());
    b=b+d;
    try
    {
        String query = "update new_account set balance='"+String.valueOf(b)+"',deposit_date='"+date+"',"
          + "last_deposit='"+String.valueOf(d)+"' where account='"+acc_id.getText()+"'";                
           
       int row = Connect.st.executeUpdate(query);
       if(row>0)
       {
           JOptionPane.showMessageDialog(rootPane,"Your Account has been credited with Rs."+d+"\nnow your Account balnce is Rs."+b);
          
       }
       String query1 = "insert into transaction1 (transid,account,action,date,amount) values "
               + "('"+tr_id.getText()+"','"+acc_id.getText().trim()+"','deposit',"
               + "'"+date+"','"+String.valueOf(d)+"')";
       int row1 = Connect.st.executeUpdate(query1);
       if(row1>0)
       {
           JOptionPane.showMessageDialog(rootPane,"Transaction Successfull");
           dispose();
       }    
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    
}//GEN-LAST:event_jButton2ActionPerformed

private void depositKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depositKeyTyped
// TODO add your handling code here:
    if(!Character.isDigit(evt.getKeyChar()))
    {
        evt.consume();
    }
}//GEN-LAST:event_depositKeyTyped

private void acc_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_idActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_acc_idActionPerformed

private void tr_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tr_idActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tr_idActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acc_id;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField c_name;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextField deposit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label;
    private javax.swing.JTextField tr_id;
    // End of variables declaration//GEN-END:variables
}
