/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainPage.java
 *
 * Created on 11 Jul, 2014, 9:19:18 AM
 */
package bankmanagement;

import connection.Connect;
import java.awt.*;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Kashmir Singh
 */
public class MainPage extends javax.swing.JFrame {

    /** Creates new form MainPage */
   
    public MainPage() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        pane1 = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        newbtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButton7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        admin = new javax.swing.JMenu();
        adduser = new javax.swing.JMenuItem();
        viewUsers = new javax.swing.JMenuItem();
        deleteuser = new javax.swing.JMenuItem();
        deleteallusers = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        newAcc = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        delete = new javax.swing.JMenuItem();
        deleteAll = new javax.swing.JMenuItem();
        view = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        alltrans = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        allholderDetails = new javax.swing.JMenuItem();
        holdersList = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        helpbtn = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pane1.setBackground(new java.awt.Color(-1,true));

        jToolBar1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("New Account");

        newbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NotePad.gif"))); // NOI18N
        newbtn.setToolTipText("New Account");
        newbtn.setFocusable(false);
        newbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(newbtn);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Keys.gif"))); // NOI18N
        jButton5.setToolTipText("Change Password");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);
        jToolBar1.add(jSeparator5);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.gif"))); // NOI18N
        jButton4.setToolTipText("View Acc Details");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        viewbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VIEWBY.GIF"))); // NOI18N
        viewbtn.setToolTipText("BalanceSheet");
        viewbtn.setFocusable(false);
        viewbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(viewbtn);

        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.gif"))); // NOI18N
        deletebtn.setToolTipText("Delete Account");
        deletebtn.setFocusable(false);
        deletebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deletebtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jToolBar1.add(deletebtn);
        jToolBar1.add(jSeparator6);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forms_received.gif"))); // NOI18N
        jButton6.setToolTipText("Deposit Money");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forms_distributed.gif"))); // NOI18N
        jButton8.setToolTipText("Withdraw Money");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);
        jToolBar1.add(jSeparator7);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Help.gif"))); // NOI18N
        jButton7.setToolTipText("Help");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        admin.setText("Admin");

        adduser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_reviewer.gif"))); // NOI18N
        adduser.setText("Add User");
        adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserActionPerformed(evt);
            }
        });
        admin.add(adduser);

        viewUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email_initiator.gif"))); // NOI18N
        viewUsers.setText("View All Users");
        viewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUsersActionPerformed(evt);
            }
        });
        admin.add(viewUsers);

        deleteuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_over.png"))); // NOI18N
        deleteuser.setText("Delete User");
        deleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteuserActionPerformed(evt);
            }
        });
        admin.add(deleteuser);

        deleteallusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash.gif"))); // NOI18N
        deleteallusers.setText("Delete All Users");
        deleteallusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteallusersActionPerformed(evt);
            }
        });
        admin.add(deleteallusers);

        jMenuBar1.add(admin);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        newAcc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NotePad.gif"))); // NOI18N
        newAcc.setText("New Account");
        newAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccActionPerformed(evt);
            }
        });
        jMenu1.add(newAcc);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Keys.gif"))); // NOI18N
        jMenuItem11.setText("Change Password");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bank.gif"))); // NOI18N
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next_1.gif"))); // NOI18N
        jMenuItem5.setText("Deposit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/prev.gif"))); // NOI18N
        jMenuItem4.setText("Withdraw");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator1);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/end_review.gif"))); // NOI18N
        jMenuItem10.setText("Modify Account");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        delete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_over.png"))); // NOI18N
        delete.setText("Delete Account");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jMenu2.add(delete);

        deleteAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        deleteAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.gif"))); // NOI18N
        deleteAll.setText("Delete All Accounts");
        deleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllActionPerformed(evt);
            }
        });
        jMenu2.add(deleteAll);

        jMenuBar1.add(jMenu2);

        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.gif"))); // NOI18N
        jMenuItem2.setText("Account Information");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        view.add(jMenuItem2);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shownav.gif"))); // NOI18N
        jMenuItem7.setText("Balance Sheet");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        view.add(jMenuItem7);
        view.add(jSeparator3);

        alltrans.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        alltrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sync.gif"))); // NOI18N
        alltrans.setText("All Transactions");
        alltrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alltransActionPerformed(evt);
            }
        });
        view.add(alltrans);
        view.add(jSeparator4);

        allholderDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        allholderDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/distribute_form.gif"))); // NOI18N
        allholderDetails.setText("Navigate Account Holders Detalis");
        allholderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allholderDetailsActionPerformed(evt);
            }
        });
        view.add(allholderDetails);

        holdersList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        holdersList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paste.gif"))); // NOI18N
        holdersList.setText("All Account Holders List");
        holdersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdersListActionPerformed(evt);
            }
        });
        view.add(holdersList);
        view.add(jSeparator2);

        jMenuBar1.add(view);

        jMenu3.setText("Format");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JColorChooser.gif"))); // NOI18N
        jMenuItem6.setText("Change Background");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu8.setText("Window");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JDesktop.gif"))); // NOI18N
        jMenuItem1.setText("Close Activated Window");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JTabbedPane.gif"))); // NOI18N
        jMenuItem8.setText("Close All Windows");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenuBar1.add(jMenu8);

        helpbtn.setText("Help");
        helpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpbtnActionPerformed(evt);
            }
        });

        jMenuItem9.setText("About");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        helpbtn.add(jMenuItem9);

        jMenuItem12.setText("Keyboard Shortcuts");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        helpbtn.add(jMenuItem12);

        jMenuBar1.add(helpbtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
            .addComponent(pane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 AccDetails ac ; 
  Delete d ;
  AccHoldersDetails ad;
  NewAcc n;
   ModifyAcc m ;
   HoldersList h ;
   AddUser au ;
   AllUsers alu ;
   DeleteUser du ;
   Deposit dp ;
    Withdraw w ;
    Balancesheet1 b;
    ChangePassword cp;
    AllTrans at;
    Shortcuts sh;
    About abt;
    
 
private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
// TODO add your handling code here:
    Color c1 = JColorChooser.showDialog(pane1, null, Color.yellow);
    pane1.setBackground(c1);
    pane1.repaint();
    
}//GEN-LAST:event_jMenuItem6ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
 ac = new AccDetails(); 
 MainPage.pane1.add(ac);
 ac.setVisible(true); 
   
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
// TODO add your handling code here:
   
  d = new Delete();
  MainPage.pane1.add(d);
  d.setVisible(true);
   
}//GEN-LAST:event_deleteActionPerformed

private void allholderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allholderDetailsActionPerformed
// TODO add your handling code here:
    ad = new AccHoldersDetails();
    MainPage.pane1.add(ad);
    ad.setVisible(true);
}//GEN-LAST:event_allholderDetailsActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
   String checkAccess = Login.check;
   if(checkAccess.equals("admin"))
   {
       JOptionPane.showMessageDialog(null,"Welcome Admin");
       
   }
   else if(checkAccess.equals("Manager"))
       
   {
       JOptionPane.showMessageDialog(null,"Welcome Manager");
       adduser.setEnabled(false);
       viewUsers.setEnabled(false);
       deleteuser.setEnabled(false);
       deleteallusers.setEnabled(false);
       deleteAll.setEnabled(false);
       allholderDetails.setEnabled(false);
       
      
   }
   else if(checkAccess.equals("User"))
   {
       JOptionPane.showMessageDialog(null,"welcome User");
       adduser.setEnabled(false);
       viewUsers.setEnabled(false);
       deleteuser.setEnabled(false);
       deleteallusers.setEnabled(false);
       deleteAll.setEnabled(false);
       allholderDetails.setEnabled(false);
       newAcc.setEnabled(false);
       delete.setEnabled(false);
       holdersList.setEnabled(false);
       alltrans.setEnabled(false);
       newbtn.setEnabled(false);
       deletebtn.setEnabled(false);
       
       
       
       
   }
}//GEN-LAST:event_formWindowOpened

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
// TODO add your handling code here:
  /* Exit ex = new Exit();
   MainPage.pane1.add(ex);
   ex.setVisible(true);  */
    int a= JOptionPane.showConfirmDialog(this,"Are you sure you want to exit?");
    if(a==0)
    {
        System.exit(1);
    }
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void newAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccActionPerformed
// TODO add your handlif(!setVisible()ing code here:
   
    
   n = new NewAcc();
    pane1.add(n);
    n.setVisible(true);
    
    
    
}//GEN-LAST:event_newAccActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
    try
    {    
    pane1.getSelectedFrame().dispose();
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(rootPane,"There is no active Window");
    }
    
    
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
// TODO add your handling code here:
   m = new ModifyAcc();
    pane1.add(m);
    m.setVisible(true);
}//GEN-LAST:event_jMenuItem10ActionPerformed

private void holdersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdersListActionPerformed
// TODO add your handling code here:
    h = new HoldersList();
    pane1.add(h);
    h.setVisible(true);
}//GEN-LAST:event_holdersListActionPerformed

private void adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserActionPerformed
// TODO add your handling code here:
    au = new AddUser();
    pane1.add(au);
    au.setVisible(true);
}//GEN-LAST:event_adduserActionPerformed

private void viewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUsersActionPerformed
// TODO add your handling code here:
    alu = new AllUsers();
    pane1.add(alu);
    alu.setVisible(true);
}//GEN-LAST:event_viewUsersActionPerformed

private void deleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteuserActionPerformed
// TODO add your handling code here:
   du = new DeleteUser();
    pane1.add(du);
    du.setVisible(true);
}//GEN-LAST:event_deleteuserActionPerformed

private void deleteallusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteallusersActionPerformed
// TODO add your handling code here:
    int a = JOptionPane.showConfirmDialog(rootPane,"Are you sure you want to delete all Users");
    if(a==0)
    {
        try
        {
            Connect.getConnection();
            String query1 = "select password from login where user='admin'";
            ResultSet rs = Connect.st.executeQuery(query1);
            rs.first();
            String password = rs.getString("password");
            String query = "delete from login";
            int row = Connect.st.executeUpdate(query);
            if(row>0)
            {
                
                String query2="insert into login (user,password,access) values ('admin','"+password+"','admin')";
                int row1 = Connect.st.executeUpdate(query2);
                if(row1>0)
                {
                    JOptionPane.showMessageDialog(rootPane,"All other Users Deleted ");
                }
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }   
    }
}//GEN-LAST:event_deleteallusersActionPerformed

private void deleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllActionPerformed
// TODO add your handling code here:
    int a = JOptionPane.showConfirmDialog(rootPane,"Are you sure you want to delete all Account Ids");
    if(a==0)
    {
        try
        {
           
             String query3= "delete from transaction1";
             int row3 = Connect.st.executeUpdate(query3);
             String query = "delete from new_account";
            int row = Connect.st.executeUpdate(query);
            if(row>0 && row3>3)
            {
                    JOptionPane.showMessageDialog(rootPane,"All Account ID Deleted");
            }
            else 
               JOptionPane.showMessageDialog(rootPane,"No Account ID exists");

        }
        catch(Exception e)
        {
            System.out.println(e);
        }   
    }
}//GEN-LAST:event_deleteAllActionPerformed

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
// TODO add your handling code here:
   dp = new Deposit();
    pane1.add(dp);
    dp.setVisible(true);
}//GEN-LAST:event_jMenuItem5ActionPerformed

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
// TODO add your handling code here:
    w =new Withdraw();
    pane1.add(w);
    w.setVisible(true);
}//GEN-LAST:event_jMenuItem4ActionPerformed

private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
// TODO add your handling code here:
    
     b=new Balancesheet1();
    pane1.add(b);
    b.setVisible(true);
}//GEN-LAST:event_jMenuItem7ActionPerformed

private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

}//GEN-LAST:event_jMenu1ActionPerformed

private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
// TODO add your handling code here:
   cp = new ChangePassword();
    pane1.add(cp);
    cp.setVisible(true);
}//GEN-LAST:event_jMenuItem11ActionPerformed

private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_viewActionPerformed

private void alltransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alltransActionPerformed
// TODO add your handling code here:
   at = new AllTrans();
    pane1.add(at);
    at.setVisible(true);
}//GEN-LAST:event_alltransActionPerformed

private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jMenu8ActionPerformed

private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
// TODO add your handling code here:
       int i;
       JInternalFrame frame[]=pane1.getAllFrames();
       for(i=0;i<frame.length;i++)
       {
          frame[i].dispose();
       }
       if(i==0)
       {
            JOptionPane.showMessageDialog(rootPane,"No Window opened");
       }  
}//GEN-LAST:event_jMenuItem8ActionPerformed

private void newbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbtnActionPerformed
// TODO add your handling code here:
    n=new NewAcc();
    pane1.add(n);
    n.setVisible(true);
}//GEN-LAST:event_newbtnActionPerformed

private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
// TODO add your handling code here:
  b = new Balancesheet1(); 
 MainPage.pane1.add(b);
 b.setVisible(true);  
}//GEN-LAST:event_viewbtnActionPerformed

private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
// TODO add your handling code here:
     d = new Delete();
  MainPage.pane1.add(d);
  d.setVisible(true);
    
}//GEN-LAST:event_deletebtnActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
     ac = new AccDetails(); 
 MainPage.pane1.add(ac);
 ac.setVisible(true);  
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
   cp = new ChangePassword();
    pane1.add(cp);
    cp.setVisible(true); 
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
     w =new Withdraw();
    pane1.add(w);
    w.setVisible(true);
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
    dp = new Deposit();
    pane1.add(dp);
    dp.setVisible(true);
}//GEN-LAST:event_jButton6ActionPerformed

private void helpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpbtnActionPerformed

}//GEN-LAST:event_helpbtnActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
    sh =new Shortcuts();
    pane1.add(sh);
    sh.setVisible(true);
}//GEN-LAST:event_jButton7ActionPerformed

private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
// TODO add your handling code here:
    sh =new Shortcuts();
    pane1.add(sh);
    sh.setVisible(true);
}//GEN-LAST:event_jMenuItem12ActionPerformed

private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
// TODO add your handling code here:
    abt =new About();
    pane1.add(abt);
    abt.setVisible(true);
}//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adduser;
    private javax.swing.JMenu admin;
    private javax.swing.JMenuItem allholderDetails;
    private javax.swing.JMenuItem alltrans;
    private javax.swing.JMenuItem delete;
    private javax.swing.JMenuItem deleteAll;
    private javax.swing.JMenuItem deleteallusers;
    private javax.swing.JButton deletebtn;
    private javax.swing.JMenuItem deleteuser;
    private javax.swing.JMenu helpbtn;
    private javax.swing.JMenuItem holdersList;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem newAcc;
    private javax.swing.JButton newbtn;
    public static javax.swing.JDesktopPane pane1;
    private javax.swing.JMenu view;
    private javax.swing.JMenuItem viewUsers;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
