/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Withdraw.java
 *
 * Created on 27 Jul, 2014, 1:44:17 AM
 */
package bankmanagement;
import connection.Connect;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author Kashmir Singh
 */
public class Withdraw extends javax.swing.JInternalFrame {

    /** Creates new form Withdraw */
    public Withdraw() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    String date;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        acc_id = new javax.swing.JTextField();
        tr_id = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        c_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        withdraw = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();

        setClosable(true);
        setTitle("WITHDRAW MONEY");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(-10197846,true));

        jLabel3.setBackground(new java.awt.Color(-16777216,true));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel3.setForeground(new java.awt.Color(-1,true));
        jLabel3.setText("Withdraw Money");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(-1,true));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true), 3));

        label.setFont(new java.awt.Font("Dialog", 2, 14));
        label.setForeground(new java.awt.Color(-65536,true));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel7.setText("Transaction ID");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel1.setText("Account ID");

        acc_id.setFont(new java.awt.Font("Dialog", 0, 18));
        acc_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_idActionPerformed(evt);
            }
        });
        acc_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                acc_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                acc_idKeyTyped(evt);
            }
        });

        tr_id.setEditable(false);
        tr_id.setFont(new java.awt.Font("Dialog", 0, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(acc_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(tr_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tr_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acc_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(-1,true));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true), 3));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel2.setText("Customer Name");

        c_name.setEditable(false);
        c_name.setFont(new java.awt.Font("Dialog", 0, 14));
        c_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nameActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(-10197846,true));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton1.setForeground(new java.awt.Color(-1,true));
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(-10197846,true));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton2.setForeground(new java.awt.Color(-1,true));
        jButton2.setText("WITHDRAW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        withdraw.setFont(new java.awt.Font("Dialog", 0, 14));
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });
        withdraw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                withdrawKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel6.setText("Withdraw Amount");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel4.setText("Balance");

        balance.setEditable(false);
        balance.setFont(new java.awt.Font("Dialog", 0, 14));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel5.setText("Date");

        dateField.setEditable(false);
        dateField.setFont(new java.awt.Font("Dialog", 0, 14));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateField)
                                    .addComponent(withdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(balance)
                                    .addComponent(c_name, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButton1)
                        .addGap(106, 106, 106)
                        .addComponent(jButton2)))
                .addContainerGap(101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(c_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed

}//GEN-LAST:event_withdrawActionPerformed

private void acc_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_idActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_acc_idActionPerformed

private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
// TODO add your handling code here:
    tr_id.setEditable(false);
    c_name.setEditable(false);
    balance.setEditable(false);
    try
    {
        Connect.getConnection();
        String query = "select count(*) from transaction1";
        ResultSet rs = Connect.st.executeQuery(query);
        rs.first();
        int count = rs.getInt(1);
        rs.close();
        if(count==0)
        {
            tr_id.setText(String.valueOf(count+100));
        }
        else
        {
            String query1 = "select transid from transaction1";
            rs = Connect.st.executeQuery(query1);
            rs.last();
            int i = Integer.parseInt(rs.getString(1));
            i=i+1;
            tr_id.setText(String.valueOf(i));
            
        }
        date=DateToday.getDate();
        dateField.setText(DateToday.day+"-"+DateToday.monthName+"-"+DateToday.year);
    }
    catch(Exception e)
    {
        System.out.println(e);
    }

}//GEN-LAST:event_formInternalFrameOpened

private void acc_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acc_idKeyTyped
// TODO add your handling code here:
    if(!Character.isDigit(evt.getKeyChar()))
    {
        evt.consume();
    }
}//GEN-LAST:event_acc_idKeyTyped

private void acc_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acc_idKeyReleased
// TODO add your handling code here:
    if(!acc_id.getText().trim().equals(""))
     {
       try
       {
        
        Connect.getConnection();
        String query = "select name,balance from new_account where account='"+acc_id.getText()+"'";
        ResultSet rs = Connect.st.executeQuery(query);
        if(rs.next())
        {
            label.setText("valid Account ID");
            c_name.setText(rs.getString("name"));
            balance.setText(rs.getString("balance"));
        } 
        else
        {
        label.setText("invalid account ID");    
        c_name.setText("");
        balance.setText("");
        }
    }   
        catch(Exception e)
        {
            System.out.println(e);
        }
     }
    else
    {
       label.setText("Enter account Id");
    }
}//GEN-LAST:event_acc_idKeyReleased

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
   
    try
    {
        if(!acc_id.getText().trim().equals(""))
    {
        Connect.getConnection();
        String query = "select name,balance from new_account where account='"+acc_id.getText()+"'";
        ResultSet rs = Connect.st.executeQuery(query);
        if(!rs.next())
        {
            JOptionPane.showMessageDialog(rootPane,"Enter correct Account ID");
            return;
        }
    }
       else
        {
            JOptionPane.showMessageDialog(rootPane,"Enter Account Id for the transaction");
            return;
         }
        
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    
    if(withdraw.getText().equals(""))
    {
        JOptionPane.showMessageDialog(rootPane,"Enter the amount to be withdrawn ");
        return;
    }
    else if(withdraw.getText().length()<3)
    {
        JOptionPane.showMessageDialog(rootPane,"Minimum limit to withdraw money is Rs.100 ");
        withdraw.setText("");
        return;
    }
    
    int b = Integer.parseInt(balance.getText());
    int d = Integer.parseInt(withdraw.getText());
    b=b-d;
    if(b>=1000)
    {
    try
    {
        String query = "update new_account set balance='"+String.valueOf(b)+"',withdraw_date='"+date+"',"
          + "last_withdraw='"+String.valueOf(d)+"' where account='"+acc_id.getText()+"'";                
           
       int row = Connect.st.executeUpdate(query);
       if(row>0)
       {
           JOptionPane.showMessageDialog(rootPane,"Rs."+d+" has been withdrawn\nNow your Account balnce is Rs."+b);
          
       }
       String query1 = "insert into transaction1 (transid,account,action,date,amount) values "
               + "('"+tr_id.getText()+"','"+acc_id.getText().trim()+"','Withdraw',"
               + "'"+date+"',"
               + "'"+String.valueOf(d)+"')";
       int row1 = Connect.st.executeUpdate(query1);
       if(row1>0)
       {
           JOptionPane.showMessageDialog(rootPane,"Transaction Successfull");
          dispose();
       }    
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    }
    else
    {
        JOptionPane.showMessageDialog(rootPane,"Not sufficient balance in Account\nYou have to maintain min. balance of Rs1000 in your Account");
        withdraw.setText("");
        return;
    }
      
}//GEN-LAST:event_jButton2ActionPerformed

private void withdrawKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_withdrawKeyTyped
// TODO add your handling code here:
    if(!Character.isDigit(evt.getKeyChar()))
    {
        evt.consume();
    }
}//GEN-LAST:event_withdrawKeyTyped

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void c_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_c_nameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acc_id;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField c_name;
    private javax.swing.JTextField dateField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label;
    private javax.swing.JTextField tr_id;
    private javax.swing.JTextField withdraw;
    // End of variables declaration//GEN-END:variables
}
